"id": "5"
"pattern": "menot.csv"
"account": "menot"
"delimiter": ","
"date_format": "%d.%m.%Y"
"day_first": "TRUE"
"columns":
  "date": "date"
  "amount": "amount"
  "description": "description"
  "info": "info"
